names =[ 
    "Aarav Sharma", "Ishaan Singh", "Ananya Reddy", "Diya Patel", "Vihaan Kumar",
    "Advait Verma", "Riya Nair", "Arjun Gupta", "Karthik Iyer", "Nisha Das",
    "Sneha Joshi", "Varun Bose", "Yash Chatterjee", "Meera Menon", "Rohan Nambiar",
    "Saanvi Ghosh", "Pranav Pillai", "Neha Shetty", "Siddharth Rao", "Pooja Shah",
    "Tanvi Suresh", "Ayaan Desai", "Gaurav Kapoor", "Shreya Saxena", "Krishna Bhatt",
    "Aditi Prasad", "Rajesh Mehta", "Mitali Kulkarni", "Raghav Tripathi", "Tara Bansal",
    "Vikram Chauhan", "Simran Lal", "Harshit Rathi", "Ira Mukherjee", "Dev Bhattacharya",
    "Kabir Kohli", "Lavanya Raina", "Mahesh Dubey", "Nandini Yadav", "Om Prakash",
    "Preeti Dutta", "Quasar Hussain", "Ravi Pathak", "Surbhi Malhotra", "Tushar Ghoshal",
    "Usha Raman", "Vani Deshmukh", "Wasim Farooqui", "Xena Borkar", "Yamini Pillai",
    "Zoya Merchant", "Abhinav Joshi", "Bhavya Kaur", "Chirag Sehgal", "Deepali Nayak",
    "Eklavya Rana", "Farhan Siddiqui", "Gita Sethi", "Himanshu Tandon", "Indira Naidu",
    "Jai Agarwal", "Kajal Thakur", "Leena Pandey", "Madhav Rajan", "Nikhil Bansode",
    "Ojas Chawla", "Piyush Khurana", "Rashmi Choksi", "Saket Jain", "Tejaswi Pawar",
    "Utkarsh Saxena", "Vaishnavi Modi", "Waris Shah", "Xavier Fernandes", "Yuvraj Singh",
    "Zeenat Qureshi", "Aman Khatri", "Barkha Rawat", "Chetan Bhatt", "Dhriti Sahu",
    "Esha Dugar", "Faizal Ansari", "Garima Solanki", "Hriday Shekhar", "Ishita Mistry",
    "Jatin Wadhwa", "Kritika Kohli", "Lakshya Kapoor", "Manya Sharma", "Naman Jha",
    "Oorja Vyas", "Puneet Kukreja", "Riddhi Shah", "Saurabh Tyagi", "Tanya Sinha",
    "Urvashi Dixit", "Vedant Shah", "Waseem Sheikh", "Xara Sanghvi", "Yashvi Parekh",
    "Zaid Merchant","Aakash Rathi", "Aaliya Noor", "Amrita Vyas", "Aparna Kaur", "Arvind Pillai",
    "Ashwin Desai", "Avantika Iyer", "Bhaskar Yadav", "Bindiya Shah", "Charan Nair",
    "Chitra Balan", "Darshan Rao", "Deepika Sahu", "Dhanush Reddy", "Divyansh Kohli",
    "Ekta Kapoor", "Farida Hussain", "Girish Raina", "Harini Subramaniam", "Ila Joshi",
    "Imran Qureshi", "Isha Chopra", "Jaspreet Singh", "Jhanvi Shetty", "Juhi Dey",
    "Kiran Sharma", "Krish Bhat", "Kunal Rathi", "Latika Verma", "Luv Jain",
    "Mahi Chauhan", "Manoj Reddy", "Mihika Shah", "Moksha Mehra", "Namrata Dubey",
    "Nayana Pillai", "Neeraj Ghosh", "Nehal Pathak", "Nikhita Rao", "Nirav Shah",
    "Palak Desai", "Paras Bhatia", "Payal Bhardwaj", "Prakash Sinha", "Prisha Arora",
    "Priyanka Seth", "Rachit Kapoor", "Rajvi Patel", "Rhea Mahajan", "Ritesh Basu",
    "Roshni Shah", "Ruhi Sinha", "Sahil Sharma", "Sakshi Joshi", "Sameer Tiwari",
    "Samiksha Nair", "Sanaya Kapadia", "Sanjana Menon", "Sarthak Gupta", "Seema Rathod",
    "Shanaya Dixit", "Shivam Tripathi", "Shravan Mehta", "Shweta Dugar", "Siddhi Shah",
    "Sonali Ghosh", "Sonia Khanna", "Soumya Shekhar", "Sudhir Pillai", "Sugandha Dubey",
    "Sukriti Das", "Sumanth Rao", "Swati Kulkarni", "Tanisha Reddy", "Tapasya Iyer",
    "Taran Khurana", "Tarun Chawla", "Trisha Modi", "Tulsi Bhatt", "Tushita Bose",
    "Ujwal Rawat", "Uma Mahesh", "Urja Pandey", "Vaibhav Rana", "Varsha Chauhan",
    "Veer Singh", "Vibha Rathi", "Vidit Jain", "Vimal Patel", "Vinayak Nambiar",
    "Vishal Prasad", "Yamini Chauhan", "Yashwardhan Goyal", "Yuvika Bansal", "Zara Hussain",
    "Zubin Irani", "Zulekha Khan", "Zoheb Ansari", "Zainab Qadri",
    "Aadhya Sethi", "Aarohi Bhandari", "Abhishek Solanki", "Adarsh Shetty", "Akira Iqbal",
    "Amey Kulkarni", "Amol Sharma", "Anaya Chauhan", "Aniket Kaur", "Anirudh Bhatt",
    "Anushka Rathore", "Arya Mahajan", "Aryan Kapoor", "Avika Joshi", "Ayushi Seth",
    "Bhargav Mehta", "Bhuvana Ramesh", "Chaitali Basu", "Charvi Saxena", "Daksh Jain",
    "Damini Deshmukh", "Darika Pillai", "Deeksha Shah", "Devika Rao", "Dhruvi Bhatt",
    "Diksha Khanna", "Divit Dubey", "Eshanvi Patel", "Falguni Shah", "Gauransh Bhaskar",
    "Gulzar Hussain", "Hansika Iyer", "Hardik Kohli", "Harshitha Yadav", "Hetvi Shah",
    "Hridaan Chauhan", "Ishaanvi Seth", "Jasleen Bedi", "Jayant Gupta", "Jeet Arora",
    "Jivika Sinha", "Kairav Verma", "Kajal Sharma", "Kanishk Rathi", "Kashish Jindal",
    "Keya Shetty", "Kripa Bhatia", "Lakshya Nair", "Lisha Chawla", "Madhuri Pillai",
    "Mahika Kapoor", "Manvi Sinha", "Moksh Goyal", "Mrunal Joshi", "Myra Shah",
    "Naira Desai", "Naitik Gupta", "Namish Thakur", "Navya Reddy", "Nehal Tandon",
    "Niharika Rathi", "Nilesh Sharma", "Nimrit Arora", "Nishka Bansal", "Ojasvi Pillai",
    "Omkar Sahu", "Padma Iyer", "Pari Shah", "Parthiv Kaur", "Pihu Reddy",
    "Pradyumna Tiwari", "Prakriti Shah", "Pranitha Naik", "Prisha Bansode", "Purvi Choksi",
    "Rachana Shetty", "Rajat Vyas", "Rajveer Kapoor", "Reyansh Mehra", "Ridham Jain",
    "Riona Mahesh", "Ritika Joshi", "Ronit Deshmukh", "Saanvika Nambiar", "Sahil Pathak",
    "Saketh Babu", "Samaira Sethi", "Sanchit Kumar", "Sanya Iyer", "Saransh Dubey",
    "Shaurya Chauhan", "Shravya Pillai", "Shubham Dey", "Simar Khurana", "Suhana Rajput",
    "Suryansh Gupta", "Tanishk Kapoor", "Tara Rathod", "Triveni Ghosh", "Vedika Menon",
    "Aarini Rathi", "Aayush Jha", "Abha Kapoor", "Aditya Bhatia", "Agastya Rao",
    "Aisha Khanna", "Akanksha Pillai", "Alok Mehra", "Amrita Saini", "Anandita Singh",
    "Anay Shah", "Anshuman Pathak", "Aradhya Chauhan", "Arhaan Bhaskar", "Arpita Sen",
    "Ashika Verma", "Ayansh Das", "Ayra Kulkarni", "Bhakti Shetty", "Bhavin Iyer",
    "Chahak Sharma", "Charvi Menon", "Chirayu Saxena", "Daksha Bedi", "Damodar Tiwari",
    "Darshit Chauhan", "Deepanshi Jindal", "Devansh Rathore", "Dhairya Patel", "Dhriti Kapoor",
    "Dhwani Shah", "Divyam Gupta", "Eesha Rawat", "Ekagra Singh", "Ekisha Bansal",
    "Garv Kohli", "Gitali Joshi", "Guneet Nair", "Hansa Dubey", "Harshita Pillai",
    "Himika Shah", "Iravati Arora", "Ishaanvi Nair", "Ishita Sethi", "Iti Mahajan",
    "Jahnavi Kapoor", "Janya Desai", "Jaswin Ghosh", "Jiya Shekhar", "Joshita Iyer",
    "Juveria Qureshi", "Kiaan Sharma", "Kirit Bhatt", "Kriday Sahu", "Kripa Jain",
    "Lakshit Kohli", "Lavesh Kapoor", "Lavina Shetty", "Madhavi Rao", "Mahin Verma",
    "Manasvi Shah", "Meenal Deshmukh", "Mihir Mehta", "Misha Pathak", "Moksha Bhatt",
    "Mrunmayi Sinha", "Myra Yadav", "Naisha Joshi", "Naksh Shah", "Namratha Chawla",
    "Navdeep Kapoor", "Navish Saxena", "Neelima Bedi", "Nidhi Chauhan", "Niharika Tandon",
    "Nilesh Shetty", "Nimai Iyer", "Ojas Shah", "Onkar Khanna", "Palvi Rathi",
    "Parth Gupta", "Pranit Kapoor", "Pranshi Yadav", "Pratyush Mehra", "Purab Bansode",
    "Rajanya Sen", "Ranya Jindal", "Riddhima Rathore", "Rishaan Pillai", "Ritika Tiwari",
    "Ronav Dubey", "Saanchi Kapoor", "Sadhil Jain", "Sagarika Arora", "Samarth Bhaskar",
    "Sanyukta Nair", "Sarthak Deshmukh", "Shivanya Reddy", "Shray Pathak", "Swara Kohli",
       "Aadit Bhalla", "Aahana Chopra", "Aarush Desai", "Abhiraj Sahu", "Adhira Pillai",
    "Advika Reddy", "Agney Chauhan", "Ahana Sinha", "Akshaj Sharma", "Alisha Bhatt",
    "Amogh Jain", "Anaya Kapoor", "Anshika Saxena", "Arhaan Ghosh", "Arnav Shah",
    "Aryahi Joshi", "Avni Khanna", "Ayanshi Menon", "Bhairav Dubey", "Bhavana Seth",
    "Bhuvan Jindal", "Chaitanya Kapoor", "Chandan Kohli", "Charan Rathore", "Charvi Yadav",
    "Dakshit Tandon", "Darsheel Deshmukh", "Deepit Pathak", "Devisha Pillai", "Dhruv Mehra",
    "Dikshita Rathi", "Divyanshi Verma", "Eshan Shetty", "Eshika Iyer", "Faiyaz Qureshi",
    "Gaurika Bedi", "Gitanjali Dubey", "Gunjan Chauhan", "Hanshika Bansal", "Harini Shah",
    "Harshika Kapoor", "Heer Nair", "Hridhaan Rao", "Ira Sharma", "Ishanvi Patel",
    "Ishleen Singh", "Iti Bansode", "Jairaj Pillai", "Janya Saxena", "Jayesh Menon",
    "Jivansh Kohli", "Juhi Pathak", "Kahaan Dubey", "Kairavi Bhatt", "Kamakshi Shekhar",
    "Kanan Verma", "Kiaan Singh", "Kriti Kapoor", "Krishiv Iyer", "Kshirja Shah",
    "Lavith Rathi", "Liyana Sethi", "Maanas Desai", "Mahira Joshi", "Maitreya Pillai",
    "Meera Chauhan", "Mehul Jain", "Mihika Rao", "Mira Kapoor", "Mishka Sharma",
    "Mitansh Pathak", "Mohak Bedi", "Mysha Dubey", "Naitik Shah", "Namya Menon",
    "Navika Rathi", "Nehan Bhaskar", "Neysa Kapoor", "Niharika Pillai", "Nimay Kohli",
    "Nirvi Ghosh", "Omisha Shetty", "Onaya Iyer", "Parina Kapoor", "Parv Deshmukh",
    "Pragya Bansal", "Pranav Rao", "Pratyusha Verma", "Priyal Joshi", "Purab Tandon",
    "Raahi Khanna", "Rachit Shah", "Ranya Kapoor", "Reyanshi Chauhan", "Ridhaan Shekhar",
    "Ritvik Nair", "Ronav Pillai", "Saachi Ghosh", "Saanvi Verma", "Shlok Desai",
    "Shreshta Bedi", "Shubh Saxena", "Tanay Menon"
]

teacher_names = [
    ("Amit Sharma", "Male"),
    ("Rajesh Patel", "Male"),
    ("Sunita Iyer", "Female"),
    ("Kavita Nair", "Female"),
    ("Vikram Desai", "Male"),
    ("Sanjay Rao", "Male"),
    ("Poonam Shah", "Female"),
    ("Priya Menon", "Female"),
    ("Deepak Joshi", "Male"),
    ("Anjali Ghosh", "Female"),
    ("Suresh Pillai", "Male"),
    ("Manoj Mehta", "Male"),
    ("Neha Kapoor", "Female"),
    ("Shweta Sinha", "Female"),
    ("Ashok Bansal", "Male"),
    ("Sneha Verma", "Female"),
    ("Nitin Saxena", "Male"),
    ("Priti Dubey", "Female"),
    ("Ravi Khanna", "Male"),
    ("Alka Chauhan", "Female"),
    ("Kiran Shetty", "Male"),
    ("Meena Bhatt", "Female"),
    ("Ajay Chawla", "Male"),
    ("Jyoti Rathore", "Female"),
    ("Harish Deshmukh", "Male"),
    ("Madhu Tandon", "Female"),
    ("Yogesh Rathi", "Male"),
    ("Pallavi Kohli", "Female"),
    ("Umesh Tripathi", "Male"),
    ("Nandita Jain", "Female"),
    ("Prakash Pathak", "Male"),
    ("Ruchi Basu", "Female"),
    ("Girish Dubey", "Male"),
    ("Lata Sharma", "Female"),
    ("Ramesh Sen", "Male"),
    ("Varsha Bhaskar", "Female"),
    ("Mahesh Pillai", "Male"),
    ("Indira Naik", "Female"),
    ("Kailash Bedi", "Male"),
    ("Renu Ghosh", "Female"),
    ("Sameer Rao", "Male"),
    ("Sujata Das", "Female"),
    ("Naveen Yadav", "Male"),
    ("Kalpana Nair", "Female"),
    ("Ashwin Chauhan", "Male"),
    ("Rekha Jindal", "Female"),
    ("Parag Shah", "Male"),
    ("Bhavana Pillai", "Female"),
    ("Vivek Kapoor", "Male"),
    ("Shalini Arora", "Female"),
    ("Raghav Shetty", "Male"),
    ("Deepali Saxena", "Female"),
    ("Suraj Mehra", "Male"),
    ("Kamini Menon", "Female"),
    ("Akhil Desai", "Male"),
    ("Isha Sethi", "Female"),
    ("Rajiv Gupta", "Male"),
    ("Sapna Rathod", "Female"),
    ("Dinesh Iyer", "Male"),
    ("Padmini Rao", "Female"),
    ("Keshav Bhat", "Male"),
    ("Tanvi Sinha", "Female"),
    ("Siddharth Verma", "Male"),
    ("Aarti Sharma", "Female"),
    ("Shashank Pillai", "Male"),
    ("Rashmi Joshi", "Female"),
    ("Tejas Deshmukh", "Male"),
    ("Preeti Kapoor", "Female"),
    ("Arun Chauhan", "Male"),
    ("Kusum Dubey", "Female"),
    ("Vinod Menon", "Male"),
    ("Anju Khanna", "Female"),
    ("Tarun Saxena", "Male"),
    ("Geeta Ghosh", "Female"),
    ("Mukesh Bedi", "Male"),
    ("Seema Rathi", "Female"),
    ("Pradeep Sharma", "Male"),
    ("Pushpa Basu", "Female"),
    ("Akhilesh Nair", "Male"),
    ("Nilima Shah", "Female"),
    ("Bhushan Pathak", "Male"),
    ("Shobha Desai", "Female"),
    ("Narendra Rao", "Male"),
    ("Kirti Pillai", "Female"),
    ("Manish Gupta", "Male"),
    ("Sangeeta Menon", "Female"),
    ("Rahul Tripathi", "Male"),
    ("Sarita Rathore", "Female"),
    ("Hemant Iyer", "Male"),
    ("Lalita Joshi", "Female"),
    ("Devendra Sinha", "Male"),
    ("Suma Kapoor", "Female"),
    ("Om Prakash", "Male"),
    ("Chitra Dubey", "Female"),
    ("Anil Shah", "Male"),
    ("Vandana Verma", "Female")
]
